package ca.polymtl.inf2990.Etats;

/**
 * La liste des états acceptés par le gestionnaire d'états.
 * 
 * @author Charles Étienne Lalonde
 * 
 */
public enum Etats
{
	MODE_PARTIE_RAPIDE, MODE_TOURNOI, MODE_EDITION, MENU_PRINCIPAL,
	MODIFIER_ELEMENT, CHOIX_JOUEUR, CREATION_TOURNOI, CHOIX_TOURNOI,
	LISTE_PROFILS, MODE_OPTION_PARTIE_RAPIDE, MODE_OPTION_TOURNOI,
	MODE_OPTIONS, MODE_JOUER, MODE_CANAL_RADIO, MODE_LISTE_CANAUX,
	MODE_LISTE_TOURNOIS, GERER_TOURNOI
}
