/// This file is autogenerated by BuildPacketsDefinitions.py
/// DO NOT MODIFY DIRECTLY

#pragma once
#include "PacketsDefinitions.h"
#include "PacketReader.h"
#include "PacketBuilder.h"
void PacketDataChatMessage::ReceiveData(PacketReader& r)
{
    r >> mTimestamp >> mMessage >> mIsTargetGroup >> mGroupName >> mOrigin;
}

void PacketDataChatMessage::SendData(PacketBuilder& b)
{
    b << mTimestamp << mMessage << mIsTargetGroup << mGroupName << mOrigin;
}

void PacketDataGameEvent::ReceiveData(PacketReader& r)
{
    r >> mGameId >> mPlayer1Name >> mPlayer2Name >> mEvent >> mEventOnPlayerLeft;
}

void PacketDataGameEvent::SendData(PacketBuilder& b)
{
    b << mGameId << mPlayer1Name << mPlayer2Name << mEvent << mEventOnPlayerLeft;
}

void PacketDataBonus::ReceiveData(PacketReader& r)
{
    r >> mBonusPosition >> mBonusType >> mBonusAction >> mGameId >> test2;
}

void PacketDataBonus::SendData(PacketBuilder& b)
{
    b << mBonusPosition << mBonusType << mBonusAction << mGameId << test2;
}

typedef PacketDataBase* (*PacketDataGenerator)();
PacketDataBase* createPacketDataChatMessage(){return new PacketDataChatMessage();}
PacketDataBase* createPacketDataGameEvent(){return new PacketDataGameEvent();}
PacketDataBase* createPacketDataBonus(){return new PacketDataBonus();}
const PacketDataGenerator generators[3] =            
{                                                           
    createPacketDataChatMessage,
    createPacketDataGameEvent,
    createPacketDataBonus,
};                                                          
PacketDataBase* CreatePacketData(PacketDataTypes t)             
{                                                               
    unsigned int i = t-PT_NONE;                                     
    return i < NB_PACKETDATATYPE ? generators[i]() : NULL;                                     
}
