/// This file is autogenerated by BuildPacketsDefinitions.py
/// DO NOT MODIFY DIRECTLY

#pragma once
#include "PacketsDefinitions.h"
#include "PacketReader.h"
#include "PacketBuilder.h"
void PacketDataBonus::ReceiveData(PacketReader& r)
{
    r >> mBonusPosition >> mBonusType >> mBonusAction >> mGameId >> test2;
}

void PacketDataBonus::SendData(PacketBuilder& b)
{
    b << mBonusPosition << mBonusType << mBonusAction << mGameId << test2;
}

void PacketDataGameEvent::ReceiveData(PacketReader& r)
{
    r >> mGameId >> mPlayer1Name >> mPlayer2Name >> mEvent >> mEventOnPlayerLeft;
}

void PacketDataGameEvent::SendData(PacketBuilder& b)
{
    b << mGameId << mPlayer1Name << mPlayer2Name << mEvent << mEventOnPlayerLeft;
}

typedef PacketDataBase* (*PacketDataGenerator)();
PacketDataBase* createPacketDataBonus(){return new PacketDataBonus();}
PacketDataBase* createPacketDataGameEvent(){return new PacketDataGameEvent();}
const PacketDataGenerator generators[2] =            
{                                                           
    createPacketDataBonus,
    createPacketDataGameEvent,
};                                                          
PacketDataBase* CreatePacketData(PacketDataTypes t)             
{                                                               
    return generators[t]();                                     
}
