/// This file is autogenerated by BuildPacketsDefinitions.py
/// DO NOT MODIFY DIRECTLY

#pragma once

#include "Enum_Declarations.h"
#include <string>
#include "Vecteur.h"
#include <stdint.h>



class PacketReader;
class PacketBuilder;
enum PacketDataTypes
{
    PT_NONE=666,
    PT_PACKETDATACHATMESSAGE,
    PT_PACKETDATAEVENT,
    NB_PACKETDATATYPE,
};


class PacketDataBase{
public:
    virtual void ReceiveData(PacketReader& r) = 0;
    virtual void SendData(PacketBuilder& b) = 0;
    virtual PacketDataTypes GetType() = 0;
 };

class PacketDataChatMessage : public PacketDataBase
{
public:
    // Timestamp (should be the same as __int64)
    int64_t mTimestamp;

    // Message a envoyer
    std::string mMessage;

    // True means the target is a group, false means it's only one player
    bool mIsTargetGroup;

    // Or player name if mIsTragetGroup == false
    std::string mGroupName;

    // Mettre le nom du PC local pour eviter les loop infinies sur le network et eviter de recevoir ses propres messages
    std::string mOrigin;

    void ReceiveData(PacketReader& r);
    void SendData(PacketBuilder& b);
    PacketDataTypes GetType(){ return PT_PACKETDATACHATMESSAGE;}
};

class PacketDataEvent : public PacketDataBase
{
public:
    // Message a envoyer
    std::string mMessage;

    // Code d'erreur
    EventCodes mEventCode;

    void ReceiveData(PacketReader& r);
    void SendData(PacketBuilder& b);
    PacketDataTypes GetType(){ return PT_PACKETDATAEVENT;}
};

PacketDataBase* CreatePacketData(PacketDataTypes t);
